<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>false</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
	<PublishAot>true</PublishAot>
	<VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>

	<RootNamespace>EdfNet</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EdfNet\EdfNet.csproj" />
	<ProjectReference Include="..\EdfBinGenerator\EdfGenerator.csproj"
					  OutputItemType="Analyzer"
					  ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
