using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EdfGenerator;

[Generator]
public class EdfEnumeratorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. ПЕРВЫМ ДЕЛОМ: Регистрируем сами атрибуты, чтобы компилятор узнал о них до анализа
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("namespace EdfNet;");
        sb.AppendLine();
        sb.AppendLine("[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]");
        sb.AppendLine($"internal class {Common.SerializeAttribute} : Attribute {{ }}");
        sb.AppendLine();
        sb.AppendLine("[AttributeUsage(AttributeTargets.Property)]");
        sb.AppendLine($"internal class {Common.ArrayAttribute} : Attribute ");
        sb.AppendLine("{");
        sb.AppendLine("    public int[] Dimensions { get; set; }");
        sb.AppendLine($"   public {Common.ArrayAttribute}(params int[] dimensions) {{ Dimensions = dimensions; }}");
        sb.AppendLine("}");

        // Пост-инициализация должна быть первой!
        context.RegisterPostInitializationOutput(i => i.AddSource($"{Common.SerializeAttribute}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8)));

        // 2. Поиск классов с атрибутом [EdfSerializable]
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => Common.GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        // 3. Сборка данных для генерации (компиляция + список классов)
        IncrementalValuesProvider<INamedTypeSymbol> compilationAndClasses = classDeclarations.Select(static (s, _) => s!);

        // 4. Регистрация самого источника кода
        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) => Execute(spc, source));
    }

    private static void Execute(SourceProductionContext context, INamedTypeSymbol? structSymbol)
    {
        if (structSymbol is null) return;

        string namespaceName = structSymbol.ContainingNamespace.ToDisplayString();
        string structName = structSymbol.Name;
        string enumeratorName = $"{structName}ByteEnumerator";

        // Собираем свойства: базовые, вложенные сериализуемые и массивы
        var fields = structSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(f => !f.IsStatic
                        && (f.Type.IsCompatibleType() || f.Type is IArrayTypeSymbol)
                        && (f.DeclaredAccessibility == Accessibility.Public || f.DeclaredAccessibility == Accessibility.Internal))
            .ToList();

        if (fields.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using EdfNet.Interfaces;");
        sb.AppendLine("using EdfNet.Core;");
        sb.AppendLine("using EdfNet.Gen;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public struct {enumeratorName} : IEdfByteEnumerator<{structName}>");
        sb.AppendLine("    {");

        // Вызываем раздельные методы генерации
        GenerateFieldsAndDeclarations(sb, fields, structName);
        GenerateConstructor(sb, fields, structName, enumeratorName);
        GenerateMoveNext(sb, fields);
        GenerateCurrentIndex(sb);
        GenerateCurrentPoType(sb, fields);
        GenerateCurrentPoLen(sb, fields);
        GenerateWrite(sb, fields);
        GenerateRead(sb, fields);
        GenerateResult(sb, structName);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{structName}ByteEnumerator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    // 1. Объявления полей и внутренних энумераторов
    private static void GenerateFieldsAndDeclarations(StringBuilder sb, List<IPropertySymbol> fields, string structName)
    {
        sb.AppendLine($"        private const int FieldCount = {fields.Count};");
        sb.AppendLine($"        private readonly {structName} _instance;");
        sb.AppendLine("        private int _state;");
        sb.AppendLine();

        for (int i = 0; i < fields.Count; i++)
        {
            var fType = fields[i].Type.UnwrapNullable();

            if (fType is IArrayTypeSymbol arraySymbol)
            {
                string elemPoType = arraySymbol.ElementType.MapToPoType();
                if (!string.IsNullOrEmpty(elemPoType))
                    sb.AppendLine($"        private EdfArrayPrimitivesEnumerator<{arraySymbol.ElementType.ToDisplayString()}> _arrayEnum{i + 1};");
                else
                    sb.AppendLine($"        private EdfArrayObjectsEnumerator<{arraySymbol.ElementType.ToDisplayString()}, {arraySymbol.ElementType.Name}ByteEnumerator> _arrayEnum{i + 1};");
                sb.AppendLine($"        private bool _inArray{i + 1};");
            }
            else if (fType.IsNestedSerializable())
            {
                sb.AppendLine($"        private {fType.Name}ByteEnumerator _nestedEnum{i + 1};");
                sb.AppendLine($"        private bool _inNested{i + 1};");
            }
        }
        sb.AppendLine();
    }

    // 2. Конструктор
    private static void GenerateConstructor(StringBuilder sb, List<IPropertySymbol> fields, string structName, string enumeratorName)
    {
        sb.AppendLine($"        public {enumeratorName}({structName} instance)");
        sb.AppendLine("        {");
        sb.AppendLine("            _instance = instance;");
        sb.AppendLine("            _state = 0;");

        for (int i = 0; i < fields.Count; i++)
        {
            var f = fields[i];
            var fType = f.Type.UnwrapNullable();
            bool isNullable = f.Type.IsNullableValueType();

            if (fType is IArrayTypeSymbol arraySymbol)
            {
                string elemPoType = arraySymbol.ElementType.MapToPoType();
                string elemTypeName = arraySymbol.ElementType.ToDisplayString();
                string elemShortName = arraySymbol.ElementType.Name;
                var dims = f.ExtractArrayDimensions();
                if (!string.IsNullOrEmpty(elemPoType))
                {
                    sb.AppendLine($"            _arrayEnum{i + 1} = " +
                        $"new EdfArrayPrimitivesEnumerator<{elemTypeName}>" +
                        $"(null==instance.{f.Name} ? new {elemTypeName}[{dims}] : instance.{f.Name}, PoType.{elemPoType});");
                }
                else
                {
                    sb.AppendLine($"            _arrayEnum{i + 1} = " +
                        $"new EdfArrayObjectsEnumerator<{elemTypeName}, {elemShortName}ByteEnumerator>" +
                        $"(null==instance.{f.Name} ? new {elemTypeName}[{dims}] : instance.{f.Name}, obj => new {elemShortName}ByteEnumerator(obj));");
                }
                sb.AppendLine($"            _inArray{i + 1} = false;");
            }
            else if (fType.IsNestedSerializable())
            {
                if (isNullable)
                {
                    // Nullable-класс (SubVal?)
                    sb.AppendLine($"            _nestedEnum{i + 1} = new {fType.Name}ByteEnumerator(instance.{f.Name}.HasValue? instance.{f.Name}.HasValue : new {fType.Name}());");
                }
                else if (fType.IsReferenceType)
                {
                    // Обычный класс (class KeyVal)
                    sb.AppendLine($"            _nestedEnum{i + 1} = new {fType.Name}ByteEnumerator(instance.{f.Name} ?? new {fType.Name}());");
                }
                else
                {
                    // Обычная структура (struct SubVal)
                    sb.AppendLine($"            _nestedEnum{i + 1} = new {fType.Name}ByteEnumerator(instance.{f.Name});");
                }
                sb.AppendLine($"            _inNested{i + 1} = false;");
            }
        }
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    // 3. MoveNext
    private static void GenerateMoveNext(StringBuilder sb, List<IPropertySymbol> fields)
    {
        sb.AppendLine("        public bool MoveNext()");
        sb.AppendLine("        {");

        for (int i = 0; i < fields.Count; i++)
        {
            var fType = fields[i].Type.UnwrapNullable();
            if (fType is IArrayTypeSymbol)
                sb.AppendLine($"            if (_inArray{i + 1}) {{ if (_arrayEnum{i + 1}.MoveNext()) return true; _inArray{i + 1} = false; }}");
            else if (fType.IsNestedSerializable())
                sb.AppendLine($"            if (_inNested{i + 1}) {{ if (_nestedEnum{i + 1}.MoveNext()) return true; _inNested{i + 1} = false; }}");
        }

        sb.AppendLine("            if (_state >= FieldCount) return false;");
        sb.AppendLine("            _state++;");

        for (int i = 0; i < fields.Count; i++)
        {
            var fType = fields[i].Type.UnwrapNullable();
            if (fType is IArrayTypeSymbol)
                sb.AppendLine($"            if (_state == {i + 1}) {{ _inArray{i + 1} = true; return _arrayEnum{i + 1}.MoveNext(); }}");
            else if (fType.IsNestedSerializable())
                sb.AppendLine($"            if (_state == {i + 1}) {{ _inNested{i + 1} = true; return _nestedEnum{i + 1}.MoveNext(); }}");
        }

        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    // 4. CurrentIndex
    private static void GenerateCurrentIndex(StringBuilder sb)
    {
        sb.AppendLine("        public int CurrentIndex => _state - 1;");
        sb.AppendLine();
    }

    // 5. CurrentPoType
    private static void GenerateCurrentPoType(StringBuilder sb, List<IPropertySymbol> fields)
    {
        sb.AppendLine("        public PoType CurrentPoType => _state switch");
        sb.AppendLine("        {");

        for (int i = 0; i < fields.Count; i++)
        {
            var fType = fields[i].Type.UnwrapNullable();
            if (fType is IArrayTypeSymbol)
                sb.AppendLine($"            {i + 1} => _arrayEnum{i + 1}.CurrentPoType,");
            else if (fType.IsNestedSerializable())
                sb.AppendLine($"            {i + 1} => _nestedEnum{i + 1}.CurrentPoType,");
            else
                sb.AppendLine($"            {i + 1} => PoType.{TypeSymbolUtils.MapToPoType(fType)},");
        }

        sb.AppendLine("            _ => throw new InvalidOperationException()");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    // 6. CurrentPoLen
    private static void GenerateCurrentPoLen(StringBuilder sb, List<IPropertySymbol> fields)
    {
        sb.AppendLine("        public int CurrentPoLen");
        sb.AppendLine("        {");
        sb.AppendLine("            get");
        sb.AppendLine("            {");
        sb.AppendLine("                switch (_state)");
        sb.AppendLine("                {");
        sb.AppendLine("                    default: return 0;");

        for (int i = 0; i < fields.Count; i++)
        {
            var f = fields[i];
            var fType = f.Type.UnwrapNullable();

            if (fType is IArrayTypeSymbol)
                sb.AppendLine($"                    case {i + 1}: return _arrayEnum{i + 1}.CurrentPoLen;");
            else if (fType.IsNestedSerializable())
                sb.AppendLine($"                    case {i + 1}: return _nestedEnum{i + 1}.CurrentPoLen;");
            else if (fType.SpecialType == SpecialType.System_String)
                sb.AppendLine($"                    case {i + 1}: return EdfBinString.SizeOf(_instance.{f.Name});");
            else
                sb.AppendLine($"                    case {i + 1}: return {fType.GetPrimitiveSize()};");
        }
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

    }// 7. Write
    private static void GenerateWrite(StringBuilder sb, List<IPropertySymbol> fields)
    {
        sb.AppendLine("        public int Write(Span<byte> destination)");
        sb.AppendLine("        {");
        for (int i = 0; i < fields.Count; i++)
        {
            var fType = fields[i].Type.UnwrapNullable();
            if (fType is IArrayTypeSymbol)
                sb.AppendLine($"            if (_inArray{i + 1}) return _arrayEnum{i + 1}.Write(destination);");
            else if (fType.IsNestedSerializable())
                sb.AppendLine($"            if (_inNested{i + 1}) return _nestedEnum{i + 1}.Write(destination);");
        }
        sb.AppendLine("            switch (_state)");
        sb.AppendLine("            {");
        sb.AppendLine("                default: return 0;");

        for (int i = 0; i < fields.Count; i++)
        {
            var f = fields[i];
            var fType = f.Type.UnwrapNullable();
            bool isNullable = f.Type.IsNullableValueType();
            if (fType is IArrayTypeSymbol || fType.IsNestedSerializable())
                continue;
            if (fType.SpecialType == SpecialType.System_String)
                sb.AppendLine($"                case {i + 1}: return EdfBinString.WriteBin(_instance.{f.Name}, destination);");
            else
            {
                int size = fType.GetPrimitiveSize();
                sb.AppendLine($"                case {i + 1}: if (destination.Length < {size}) return 0;");
                if (isNullable)// Nullable-структура 
                {
                    sb.AppendLine($"                    MemoryMarshal.Write(destination, _instance.{f.Name}.GetValueOrDefault());");
                }
                else // Обычная структура (struct SubVal)
                {
                    sb.AppendLine($"                    MemoryMarshal.Write(destination, _instance.{f.Name});");
                }
                sb.AppendLine($"                    return {size};");
            }
        }
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }
    // 8. Read
    private static void GenerateRead(StringBuilder sb, List<IPropertySymbol> fields)
    {
        sb.AppendLine("        public int Read(ReadOnlySpan<byte> src)");
        sb.AppendLine("        {");
        for (int i = 0; i < fields.Count; i++)
        {
            var f = fields[i];
            var fType = f.Type.UnwrapNullable();
            if (fType is IArrayTypeSymbol)
                sb.AppendLine($"            if (_inArray{i + 1}) return _arrayEnum{i + 1}.Read(src);");
            else if (fType.IsNestedSerializable())
            {
                sb.AppendLine($"            if (_inNested{i + 1}) {{");
                sb.AppendLine($"                var readLen = _nestedEnum{i + 1}.Read(src);");
                sb.AppendLine($"                _instance.{f.Name} = _nestedEnum{i + 1}.Result;");
                sb.AppendLine($"                return readLen;"); sb.AppendLine($"            }}");
            }
        }
        sb.AppendLine("            switch (_state)");
        sb.AppendLine("            {");
        sb.AppendLine("                default: return 0;");
        for (int i = 0; i < fields.Count; i++)
        {
            var f = fields[i];
            var fType = f.Type.UnwrapNullable();
            if (fType is IArrayTypeSymbol || fType.IsNestedSerializable())
                continue;
            if (fType.SpecialType == SpecialType.System_String)
            {
                sb.AppendLine($"                case {i + 1}:");
                sb.AppendLine("                {");
                sb.AppendLine("                      var readLen = EdfBinString.ReadBin(src, out var str);");
                sb.AppendLine($"                      _instance.{f.Name} = str;");
                sb.AppendLine("                      return readLen;");
                sb.AppendLine("                }");
            }
            else
            {
                sb.AppendLine($"                case {i + 1}: _instance.{f.Name} = MemoryMarshal.Read<{fType.ToDisplayString()}>(src);");
                sb.AppendLine($"                     return {fType.GetPrimitiveSize()};");
            }
        }
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }
    // 9. Result
    private static void GenerateResult(StringBuilder sb, string structName)
    {
        sb.AppendLine($"        public {structName} Result => _instance;");
    }

}
