using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Text;

namespace EdfBinGenerator;

[Generator]
public class EdfEnumeratorGenerator : IIncrementalGenerator
{
    public const string SerializeAttribute = "EdfBinSerializableAttribute";
    public const string BinArrayAttribute = "EdfBinArrayAttribute";


    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Поиск классов с атрибутом [BinarySerializable]
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                //predicate: static (s, _) => s is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                predicate: static (s, _) => s is TypeDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        // 2. Сборка данных для генерации (компиляция + список классов)
        IncrementalValuesProvider<INamedTypeSymbol> compilationAndClasses = classDeclarations.Select(static (s, _) => s!);

        // 3. Регистрация самого источника кода
        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) => Execute(spc, source));

    }


    private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        //var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var classDeclaration = (TypeDeclarationSyntax)context.Node;
        foreach (var attributeList in classDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                // Быстрая текстовая проверка, чтобы зря не нагружать семантическую модель
                string attrName = attribute.Name.ToString();
                if (attrName != "EdfBinSerializable" && attrName != SerializeAttribute)
                    continue;

                if (context.SemanticModel.GetSymbolInfo(attribute).Symbol is IMethodSymbol attributeSymbol &&
                    attributeSymbol.ContainingType.ToDisplayString() == $"EdfNet.{SerializeAttribute}")
                {
                    return context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
                }
            }
        }
        return null;
    }
    private static bool IsComatibleType(ITypeSymbol ntype)
    {
        if (ntype == null) return false;

        bool hasAttribute = ntype.GetAttributes().Any(a =>
            a.AttributeClass?.ToDisplayString() == $"EdfNet.{SerializeAttribute}");

        return hasAttribute || !string.IsNullOrWhiteSpace(MapToPoType(ntype));
    }
    private static string MapToPoType(ITypeSymbol typeSymbol)
    {
        return typeSymbol.SpecialType switch
        {
            SpecialType.System_Byte => "Int8",
            SpecialType.System_SByte => "UInt8",
            SpecialType.System_Int16 => "Int16",
            SpecialType.System_UInt16 => "UInt16",
            SpecialType.System_Int32 => "Int32",
            SpecialType.System_UInt32 => "UInt32",
            SpecialType.System_Double => "Double",
            SpecialType.System_Single => "Single",
            SpecialType.System_Int64 => "Int64",
            SpecialType.System_UInt64 => "UInt64",
            SpecialType.System_String => "String",
            _ => string.Empty // Сюда можно добавить обработку других типов (Char, Int8 и т.д.)
        };
    }

    private static void Execute(SourceProductionContext context, INamedTypeSymbol? structSymbol)
    {
        if (structSymbol is null) return;

        string namespaceName = structSymbol.ContainingNamespace.ToDisplayString();
        string structName = structSymbol.Name;
        string enumeratorName = $"{structName}ByteEnumerator";

        // Собираем свойства: базовые типы, вложенные типы с атрибутом и любые массивы
        var fields = structSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(f => !f.IsStatic
                        && (IsComatibleType(f.Type) || f.Type is IArrayTypeSymbol)
                        && (f.DeclaredAccessibility == Accessibility.Public || f.DeclaredAccessibility == Accessibility.Internal))
            .ToList();

        if (fields.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using EdfNet;");
        sb.AppendLine("using EdfNet.Core;");
        sb.AppendLine("using EdfNet.Core.Gen;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public struct {enumeratorName} : IEdfByteEnumerator");
        sb.AppendLine("    {");
        sb.AppendLine($"        private const int FieldCount = {fields.Count};");
        sb.AppendLine($"        private {structName} _instance;");
        sb.AppendLine("        private int _state;");
        sb.AppendLine();

        // 1. Генерируем поля для вложенных энумераторов
        for (int i = 0; i < fields.Count; i++)
        {
            var f = fields[i];
            if (f.Type is IArrayTypeSymbol arraySymbol)
            {
                string elemPoType = MapToPoType(arraySymbol.ElementType);
                if (!string.IsNullOrEmpty(elemPoType))
                    sb.AppendLine($"        private EdfArrayEnumerator<{arraySymbol.ElementType.ToDisplayString()}> _arrayEnum{i + 1};");
                else
                    sb.AppendLine($"        private EdfObjectArrayEnumerator<{arraySymbol.ElementType.ToDisplayString()}, {arraySymbol.ElementType.Name}ByteEnumerator> _arrayEnum{i + 1};");
                sb.AppendLine($"        private bool _inArray{i + 1};");
            }
            else if (!string.IsNullOrEmpty(f.Type.Name) && MapToPoType(f.Type) == string.Empty)
            {
                // Это вложенная структура/класс
                sb.AppendLine($"        private {f.Type.Name}ByteEnumerator _nestedEnum{i + 1};");
                sb.AppendLine($"        private bool _inNested{i + 1};");
            }
        }
        sb.AppendLine();

        // Конструктор
        sb.AppendLine($"        public {enumeratorName}(in {structName} instance)");
        sb.AppendLine("        {");
        sb.AppendLine("            _instance = instance;");
        sb.AppendLine("            _state = 0;");
        for (int i = 0; i < fields.Count; i++)
        {
            var f = fields[i];
            if (f.Type is IArrayTypeSymbol arraySymbol)
            {
                string elemPoType = MapToPoType(arraySymbol.ElementType);
                if (!string.IsNullOrEmpty(elemPoType))
                    sb.AppendLine($"            _arrayEnum{i + 1} = instance.{f.Name} != null ? new EdfArrayEnumerator<{arraySymbol.ElementType.ToDisplayString()}>(instance.{f.Name}, PoType.{elemPoType}) : default;");
                else
                    sb.AppendLine($"            _arrayEnum{i + 1} = instance.{f.Name} != null ? new EdfObjectArrayEnumerator<{arraySymbol.ElementType.ToDisplayString()}, {arraySymbol.ElementType.Name}ByteEnumerator>(instance.{f.Name}, 0) : default;");
                sb.AppendLine($"            _inArray{i + 1} = false;");
            }
            else if (!string.IsNullOrEmpty(f.Type.Name) && MapToPoType(f.Type) == string.Empty)
            {
                string castOp = f.Type.IsValueType ? ".Value" : "";
                sb.AppendLine($"            _nestedEnum{i + 1} = instance.{f.Name} != null ? new {f.Type.Name}ByteEnumerator(instance.{f.Name}{castOp}) : default;");
                sb.AppendLine($"            _inNested{i + 1} = false;");
            }
        }
        sb.AppendLine("        }");
        sb.AppendLine();

        // MoveNext (с поддержкой удержания состояния во вложенных типах)
        sb.AppendLine("        public bool MoveNext()");
        sb.AppendLine("        {");
        for (int i = 0; i < fields.Count; i++)
        {
            var f = fields[i];
            if (f.Type is IArrayTypeSymbol)
                sb.AppendLine($"            if (_inArray{i + 1}) {{ if (_arrayEnum{i + 1}.MoveNext()) return true; _inArray{i + 1} = false; }}");
            else if (MapToPoType(f.Type) == string.Empty)
                sb.AppendLine($"            if (_inNested{i + 1}) {{ if (_nestedEnum{i + 1}.MoveNext()) return true; _inNested{i + 1} = false; }}");
        }
        sb.AppendLine("            if (_state >= FieldCount) return false;");
        sb.AppendLine("            _state++;");
        for (int i = 0; i < fields.Count; i++)
        {
            var f = fields[i];
            if (f.Type is IArrayTypeSymbol)
                sb.AppendLine($"            if (_state == {i + 1}) {{ _inArray{i + 1} = true; return _arrayEnum{i + 1}.MoveNext(); }}");
            else if (MapToPoType(f.Type) == string.Empty)
                sb.AppendLine($"            if (_state == {i + 1}) {{ _inNested{i + 1} = true; return _nestedEnum{i + 1}.MoveNext(); }}");
        }
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // CurrentIndex
        sb.AppendLine("        public int CurrentIndex => _state - 1;");
        sb.AppendLine();

        // CurrentPoType
        sb.AppendLine("        public PoType CurrentPoType => _state switch");
        sb.AppendLine("        {");
        for (int i = 0; i < fields.Count; i++)
        {
            var f = fields[i];
            if (f.Type is IArrayTypeSymbol)
                sb.AppendLine($"            {i + 1} => _arrayEnum{i + 1}.CurrentPoType,");
            else if (MapToPoType(f.Type) == string.Empty)
                sb.AppendLine($"            {i + 1} => _nestedEnum{i + 1}.CurrentPoType,");
            else
                sb.AppendLine($"            {i + 1} => PoType.{MapToPoType(f.Type)},");
        }
        sb.AppendLine("            _ => throw new InvalidOperationException()");
        sb.AppendLine("        };");
        sb.AppendLine();

        // CurrentPoLen
        sb.AppendLine("        public int CurrentPoLen");
        sb.AppendLine("        {");
        sb.AppendLine("            get");
        sb.AppendLine("            {");
        sb.AppendLine("                switch (_state)");
        sb.AppendLine("                {");
        sb.AppendLine("                    default: return 0;");
        for (int i = 0; i < fields.Count; i++)
        {
            var f = fields[i];
            if (f.Type is IArrayTypeSymbol)
                sb.AppendLine($"                    case {i + 1}: return _arrayEnum{i + 1}.CurrentPoLen;");
            else if (MapToPoType(f.Type) == string.Empty)
                sb.AppendLine($"                    case {i + 1}: return _nestedEnum{i + 1}.CurrentPoLen;");
            else if (f.Type.SpecialType == SpecialType.System_String)
                sb.AppendLine($"                    case {i + 1}: return EdfBinString.SizeOf(_instance.{f.Name});");
            else
                sb.AppendLine($"                    case {i + 1}: return CurrentPoType.GetSizeOf();");
        }
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Метод Write
        sb.AppendLine("        public int Write(Span<byte> destination)");
        sb.AppendLine("        {");
        for (int i = 0; i < fields.Count; i++)
        {
            var f = fields[i];
            if (f.Type is IArrayTypeSymbol)
                sb.AppendLine($"            if (_inArray{i + 1}) return _arrayEnum{i + 1}.Write(destination);");
            else if (MapToPoType(f.Type) == string.Empty)
                sb.AppendLine($"            if (_inNested{i + 1}) return _nestedEnum{i + 1}.Write(destination);");
        }
        sb.AppendLine("            switch (_state)");
        sb.AppendLine("            {");
        sb.AppendLine("                default: return 0;");
        for (int i = 0; i < fields.Count; i++)
        {
            var f = fields[i];
            if (f.Type is IArrayTypeSymbol || MapToPoType(f.Type) == string.Empty) continue;

            if (f.Type.SpecialType == SpecialType.System_String)
                sb.AppendLine($"                case {i + 1}: return EdfBinString.WriteBin(_instance.{f.Name}, destination);");
            else
            {
                sb.AppendLine($"                case {i + 1}: MemoryMarshal.Write(destination, ref _instance.{f.Name});");
                sb.AppendLine($"                     return CurrentPoType.GetSizeOf();");
            }
        }
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Метод Read
        sb.AppendLine("        public int Read(ReadOnlySpan<byte> src)");
        sb.AppendLine("        {");
        for (int i = 0; i < fields.Count; i++)
        {
            var f = fields[i];
            if (f.Type is IArrayTypeSymbol)
                sb.AppendLine($"            if (_inArray{i + 1}) return _arrayEnum{i + 1}.Read(src);");
            else if (MapToPoType(f.Type) == string.Empty)
            {
                sb.AppendLine($"            if (_inNested{i + 1}) {{");
                sb.AppendLine($"                var readLen = _nestedEnum{i + 1}.Read(src);");
                sb.AppendLine($"                _instance.{f.Name} = _nestedEnum{i + 1}.Result;"); sb.AppendLine($"                return readLen;"); sb.AppendLine($"            }}");
            }
        }
        sb.AppendLine("            switch (_state)");
        sb.AppendLine("            {");
        sb.AppendLine("                default: return 0;");
        for (int i = 0; i < fields.Count; i++)
        {
            var f = fields[i];
            if (f.Type is IArrayTypeSymbol || MapToPoType(f.Type) == string.Empty)
                continue;
            if (f.Type.SpecialType == SpecialType.System_String)
            {
                sb.AppendLine($"                case {i + 1}:");
                sb.AppendLine("                {");
                sb.AppendLine("                      var readLen = EdfBinString.ReadBin(src, out var str);");
                sb.AppendLine($"                      _instance.{f.Name} = str;");
                sb.AppendLine("                      return readLen;");
                sb.AppendLine("                }");
            }
            else
            {
                sb.AppendLine($"                case {i + 1}: _instance.{f.Name} = MemoryMarshal.Read<{f.Type.ToDisplayString()}>(src);");
                sb.AppendLine($"                     return CurrentPoType.GetSizeOf();");
            }
        }
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();// Результат
        sb.AppendLine($"        public object Result => _instance;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        context.AddSource($"{structName}ByteEnumerator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

}
// Хелпер для извлечения символа из контекста
public static class Extensions
{
    public static INamedTypeSymbol? GetDeclaredSymbol(this StructDeclarationSyntax syntax)
    {
        // Метод-заглушка. Roslyn предоставляет доступ к модели через семантический контекст.
        return null;
    }
}
