using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EdfGenerator;

[Generator]
public class EdfFormatterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var serializableTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is TypeDeclarationSyntax tds && tds.AttributeLists.Count > 0,
                transform: static (ctx, _) => Common.GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(serializableTypes, static (spc, types) => Execute(spc, types));
    }

    private static void Execute(SourceProductionContext context, INamedTypeSymbol? typeSymbol)
    {
        if (typeSymbol is null) return;

        string ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? ""
            : typeSymbol.ContainingNamespace.ToDisplayString();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using EdfNet.Interfaces;");
        sb.AppendLine("using EdfNet.Core;");
        sb.AppendLine("using EdfNet.Gen;");

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"using {ns};");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine();
        }

        GenerateFormatter(typeSymbol, sb, ns);
        context.AddSource($"{typeSymbol.Name}Formatter.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateFormatter(INamedTypeSymbol type, StringBuilder sb, string currentNamespace)
    {
        string typeName = type.Name;
        string formatterName = $"{type.Name}Formatter";
        sb.AppendLine($"public sealed class {formatterName} : IFormatter<{typeName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public static {formatterName} Instance = new();");
        sb.AppendLine();
        sb.AppendLine($"    public void Serialize<TWriter>(ref TWriter writer, in {typeName} val, EdfOptions options)");
        sb.AppendLine("        where TWriter : struct, IBufWriter, allows ref struct");
        sb.AppendLine("    {");
        sb.AppendLine("        writer.BeginStruct();");
        foreach (var member in GetSerializableMembers(type))
        {
            GenerateSerializeMember(sb, member, "val", currentNamespace);
        }
        sb.AppendLine("        writer.EndStruct();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public {typeName} Deserialize<TReader>(ref TReader reader, EdfOptions options)");
        sb.AppendLine("        where TReader : struct, IBufReader, allows ref struct");
        sb.AppendLine("    {");
        sb.AppendLine($"        {typeName} result = new {typeName}();");
        sb.AppendLine("        reader.ReadBeginStruct();");
        foreach (var member in GetSerializableMembers(type))
        {
            GenerateDeserializeMember(sb, member, "result", currentNamespace);
        }
        sb.AppendLine("        reader.ReadEndStruct();");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static IEnumerable<ISymbol> GetSerializableMembers(INamedTypeSymbol type)
    {
        return type.GetMembers()
            .Where(m => m is IPropertySymbol || m is IFieldSymbol)
            .Where(m => !TypeSymbolUtils.IsIgnored(m))
            .Where(m => m.DeclaredAccessibility == Accessibility.Public)
            .Where(m => !IsReadOnly(m))
            .Where(m => !(m is IFieldSymbol f && f.IsConst))
            .Where(m => !(m is IFieldSymbol f && f.IsImplicitlyDeclared))
            .Where(m => m.IsSupportedMemberType());
    }

    private static bool IsReadOnly(ISymbol symbol)
    {
        return symbol switch
        {
            IPropertySymbol p => p.IsReadOnly,
            IFieldSymbol f => f.IsReadOnly,
            _ => false
        };
    }

    private static void GenerateSerializeMember(StringBuilder sb, ISymbol member, string valVar, string currentNamespace)
    {
        string memberAccess = $"{valVar}.{member.Name}";
        var memberType = member.GetMemberType()!;
        const string i8 = "        ";

        if (member.HasAttribute(Common.ArrayAttribute))
        {
            GenerateArraySerialize(sb, member, memberAccess, currentNamespace);
            return;
        }

        if (member.IsByteArray())
        {
            byte len = member.ExtractCharArrayLength();
            sb.AppendLine($"{i8}writer.WriteCharArray({memberAccess}!, {len});");
            return;
        }

        if (memberType!.IsNullableValueType())
        {
            var underlying = memberType.UnwrapNullable();
            if (TypeSymbolUtils.IsSupportedPrimitive(underlying))
            {
                sb.AppendLine($"{i8}writer.Write({memberAccess} ?? default);");
                return;
            }
            WriteValue(sb, underlying, memberAccess, i8, currentNamespace);
            return;
        }

        WriteValue(sb, memberType, memberAccess, i8, currentNamespace);
    }

    private static void GenerateDeserializeMember(StringBuilder sb, ISymbol member, string resultVar, string currentNamespace)
    {
        string memberAccess = $"{resultVar}.{member.Name}";
        var memberType = member.GetMemberType()!;
        const string i8 = "        ";

        if (member.HasAttribute(Common.ArrayAttribute))
        {
            GenerateArrayDeserialize(sb, member, memberAccess, currentNamespace);
            return;
        }

        if (member.IsByteArray())
        {
            byte len = member.ExtractCharArrayLength();
            if (len > 0)
            {
                sb.AppendLine($"{i8}{memberAccess} = reader.ReadCharArray({len});");
            }
            else
            {
                sb.AppendLine($"{i8}/* EdfCharArray length not specified for {member.Name} */");
                sb.AppendLine($"{i8}{memberAccess} = Array.Empty<byte>();");
            }
            return;
        }

        if (memberType!.IsNullableValueType())
        {
            var underlying = memberType.UnwrapNullable();
            if (TypeSymbolUtils.IsSupportedPrimitive(underlying))
            {
                string expr = GetReadExpression(underlying, currentNamespace);
                sb.AppendLine($"{i8}{memberAccess} = {expr};");
                return;
            }
            string expr2 = GetReadExpression(underlying, currentNamespace);
            sb.AppendLine($"{i8}{memberAccess} = {expr2};");
            return;
        }

        string expr3 = GetReadExpression(memberType, currentNamespace);
        sb.AppendLine($"{i8}{memberAccess} = {expr3};");
    }

    private static void WriteValue(StringBuilder sb, ITypeSymbol type, string access, string indent, string currentNamespace)
    {
        if (TypeSymbolUtils.IsSupportedPrimitive(type))
        {
            sb.AppendLine($"{indent}writer.Write({access});");
        }
        else if (type.HasAttribute(Common.SerializeAttribute))
        {
            string typeName = TypeSymbolUtils.GetShortTypeName(type, currentNamespace);
            sb.AppendLine($"{indent}EdfProvider<{typeName}>.Formatter.Serialize(ref writer, {access}, options);");
        }
        else
        {
            sb.AppendLine($"{indent}/* Unsupported serialize type: {type.ToDisplayString()} */");
        }
    }

    private static string GetReadExpression(ITypeSymbol type, string currentNamespace)
    {
        if (type.SpecialType == SpecialType.System_String)
        {
            return "reader.ReadString()";
        }
        else if (TypeSymbolUtils.IsSupportedPrimitive(type))
        {
            string typeName = TypeSymbolUtils.GetShortTypeName(type, currentNamespace);
            return $"reader.Read<{typeName}>()";
        }
        else if (type.HasAttribute(Common.SerializeAttribute))
        {
            string typeName = TypeSymbolUtils.GetShortTypeName(type, currentNamespace);
            return $"EdfProvider<{typeName}>.Formatter.Deserialize(ref reader, options)";
        }
        else
        {
            return $"/* Unsupported deserialize type: {type.ToDisplayString()} */";
        }
    }

    private static void GenerateArraySerialize(StringBuilder sb, ISymbol member, string access, string currentNamespace)
    {
        var arrayType = member.GetMemberType() as IArrayTypeSymbol;
        var elementType = arrayType?.ElementType;
        const string i8 = "        ";
        const string i12 = "            ";

        if (elementType == null)
        {
            var named = member.GetMemberType() as INamedTypeSymbol;
            elementType = named?.TypeArguments.FirstOrDefault();
        }

        if (elementType == null || !(TypeSymbolUtils.IsSupportedPrimitive(elementType) || elementType.HasAttribute(Common.SerializeAttribute)))
        {
            sb.AppendLine($"{i8}/* Unsupported array element type for {member.Name} */");
            return;
        }

        string elemTypeName = TypeSymbolUtils.GetShortTypeName(elementType, currentNamespace);
        string defaultExpr = TypeSymbolUtils.IsSupportedPrimitive(elementType)
            ? $"default({elemTypeName})"
            : $"new {elemTypeName}()";

        sb.AppendLine($"{i8}writer.BeginArray();");
        sb.AppendLine($"{i8}if ({access} == null)");
        sb.AppendLine($"{i8}{{");
        GenerateArraySerializeLoops(sb, member, access, elementType, currentNamespace, i12, true, defaultExpr);
        sb.AppendLine($"{i8}}}");
        sb.AppendLine($"{i8}else");
        sb.AppendLine($"{i8}{{");
        GenerateArraySerializeLoops(sb, member, access, elementType, currentNamespace, i12, false, null);
        sb.AppendLine($"{i8}}}");
        sb.AppendLine($"{i8}writer.EndArray();");
    }

    private static void GenerateArraySerializeLoops(StringBuilder sb, ISymbol member, string access, ITypeSymbol elementType, string currentNamespace, string indent, bool useDefault, string? defaultExpr)
    {
        var dims = member.ExtractArrayDimensionValues();
        GenerateArraySerializeLoopsRecursive(sb, member, access, elementType, currentNamespace, dims, 0, new List<string>(), indent, useDefault, defaultExpr);
    }

    private static void GenerateArraySerializeLoopsRecursive(StringBuilder sb, ISymbol member, string access, ITypeSymbol elementType, string currentNamespace, string[] dims, int depth, List<string> indices, string indent, bool useDefault, string? defaultExpr)
    {
        if (depth >= dims.Length)
        {
            string itemAccess = useDefault ? defaultExpr! : $"{access}[{string.Join(", ", indices)}]";
            WriteValue(sb, elementType, itemAccess, indent, currentNamespace);
            return;
        }

        string idx = $"_i{depth}";
        sb.AppendLine($"{indent}for (int {idx} = 0; {idx} < {dims[depth]}; {idx}++)");
        sb.AppendLine($"{indent}{{");
        var newIndices = new List<string>(indices) { idx };
        GenerateArraySerializeLoopsRecursive(sb, member, access, elementType, currentNamespace, dims, depth + 1, newIndices, indent + "    ", useDefault, defaultExpr);
        sb.AppendLine($"{indent}}}");
    }

    private static void GenerateArrayDeserialize(StringBuilder sb, ISymbol member, string access, string currentNamespace)
    {
        var arrayType = member.GetMemberType() as IArrayTypeSymbol;
        var elementType = arrayType?.ElementType;
        bool isArray = elementType != null;
        const string i8 = "        ";

        if (!isArray)
        {
            var named = member.GetMemberType() as INamedTypeSymbol;
            elementType = named?.TypeArguments.FirstOrDefault();
        }

        if (elementType == null || !(TypeSymbolUtils.IsSupportedPrimitive(elementType) || elementType.HasAttribute(Common.SerializeAttribute)))
        {
            sb.AppendLine($"{i8}/* Unsupported array element type for {member.Name} */");
            return;
        }

        var dims = member.ExtractArrayDimensionValues();
        string arrayTypeName = isArray ? TypeSymbolUtils.GetArrayTypeName(arrayType!, currentNamespace) : member.GetMemberType()!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string elemTypeName = TypeSymbolUtils.GetShortTypeName(elementType, currentNamespace);
        string localVar = $"_{member.Name}";

        if (isArray && dims.Length > 0)
        {
            sb.AppendLine($"{i8}reader.ReadBeginArray();");
            sb.AppendLine($"{i8}{arrayTypeName} {localVar} = new {elemTypeName}[{string.Join(", ", dims)}];");
            GenerateArrayDeserializeLoops(sb, elementType, localVar, dims, 0, new List<string>(), i8, currentNamespace);
            sb.AppendLine($"{i8}reader.ReadEndArray();");
            sb.AppendLine($"{i8}{access} = {localVar};");
        }
        else
        {
            sb.AppendLine($"{i8}/* Collection deserialization not implemented for {member.Name} */");
        }
    }

    private static void GenerateArrayDeserializeLoops(StringBuilder sb, ITypeSymbol elementType, string arrayVar, string[] dims, int depth, List<string> indices, string indent, string currentNamespace)
    {
        if (depth >= dims.Length)
        {
            string indexAccess = string.Join(", ", indices);
            string expr = GetReadExpression(elementType, currentNamespace);
            sb.AppendLine($"{indent}{arrayVar}[{indexAccess}] = {expr};");
            return;
        }

        string idx = $"_i{depth}";
        sb.AppendLine($"{indent}for (int {idx} = 0; {idx} < {dims[depth]}; {idx}++)");
        sb.AppendLine($"{indent}{{");
        var newIndices = new List<string>(indices) { idx };
        GenerateArrayDeserializeLoops(sb, elementType, arrayVar, dims, depth + 1, newIndices, indent + "    ", currentNamespace);
        sb.AppendLine($"{indent}}}");
    }
}
