using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EdfGenerator;

[Generator]
public class EdfFormatterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var serializableTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is TypeDeclarationSyntax tds && tds.AttributeLists.Count > 0,
                transform: static (ctx, _) => Common.GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null)
            .Collect();

        context.RegisterSourceOutput(serializableTypes, static (spc, types) =>
        {
            if (types.IsDefaultOrEmpty) return;
            var distinctTypes = types.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>().ToList();
            if (distinctTypes.Count == 0) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            foreach (var type in distinctTypes)
            {
                if (type is null) continue;
                GenerateFormatter(type, sb);
            }

            spc.AddSource("EdfFormatters.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static void GenerateFormatter(INamedTypeSymbol type, StringBuilder sb)
    {
        string typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string formatterName = $"{type.Name}Formatter";
        string ns = type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    public sealed class {formatterName} : global::EdfNet.Interfaces.IFormatter<{typeName}>");
        sb.AppendLine("    {");

        // Serialize
        sb.AppendLine($"        public void Serialize<TWriter>(ref TWriter writer, in {typeName} value, global::EdfNet.Interfaces.EdfOptions options)");
        sb.AppendLine("            where TWriter : struct, global::EdfNet.Interfaces.IBufWriter, allows ref struct");
        sb.AppendLine("        {");
        sb.AppendLine("            writer.BeginStruct();");

        var props = GetSerializableProperties(type).ToList();
        for (int i = 0; i < props.Count; i++)
        {
            GenerateSerializeProperty(sb, props[i], "value");
        }

        sb.AppendLine("            writer.EndStruct();");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Deserialize
        sb.AppendLine($"        public {typeName} Deserialize<TReader>(ref TReader reader, global::EdfNet.Interfaces.EdfOptions options)");
        sb.AppendLine("            where TReader : struct, global::EdfNet.Interfaces.IBufReader, allows ref struct");
        sb.AppendLine("        {");
        sb.AppendLine($"            {typeName} result = new {typeName}();");
        sb.AppendLine("            reader.ReadBeginStruct();");

        for (int i = 0; i < props.Count; i++)
        {
            GenerateDeserializeProperty(sb, props[i], "result");
        }

        sb.AppendLine("            reader.ReadEndStruct();");
        sb.AppendLine("            return result;");
        sb.AppendLine("        }");

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine("}");
        }

        sb.AppendLine();
    }

    private static IEnumerable<IPropertySymbol> GetSerializableProperties(INamedTypeSymbol type)
    {
        return type.GetMembers().OfType<IPropertySymbol>()
            .Where(p => !p.GetAttributes().Any(a =>
                a.AttributeClass?.ToDisplayString() == $"{Common.Namespace}.EdfIgnoreAttribute" ||
                a.AttributeClass?.Name == "EdfIgnoreAttribute"))
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsReadOnly)
            .OrderBy(p => p.Name);
    }

    private static void GenerateSerializeProperty(StringBuilder sb, IPropertySymbol prop, string valueVar)
    {
        string propAccess = $"{valueVar}.{prop.Name}";
        var propType = prop.Type;

        if (IsIgnored(prop)) return;

        var arrayAttr = GetAttribute(prop, Common.ArrayAttribute);
        if (arrayAttr != null)
        {
            GenerateArraySerialize(sb, prop, propAccess, arrayAttr);
            return;
        }

        if (GetAttribute(prop, "EdfCharArrayAttribute") != null && propType.SpecialType == SpecialType.System_String)
        {
            sb.AppendLine($"            writer.Write({propAccess});");
            return;
        }

        if (propType.IsNullableValueType())
        {
            var underlying = propType.UnwrapNullable();
            sb.AppendLine($"            if ({propAccess}.HasValue)");
            sb.AppendLine("            {");
            sb.AppendLine($"                writer.Write(true);");
            WritePrimitiveOrComplex(sb, underlying, $"{propAccess}.Value");
            sb.AppendLine("            }");
            sb.AppendLine("            else");
            sb.AppendLine("            {");
            sb.AppendLine($"                writer.Write(false);");
            sb.AppendLine("            }");
            return;
        }

        WritePrimitiveOrComplex(sb, propType, propAccess);
    }

    private static void GenerateDeserializeProperty(StringBuilder sb, IPropertySymbol prop, string resultVar)
    {
        string propAccess = $"{resultVar}.{prop.Name}";
        var propType = prop.Type;

        if (IsIgnored(prop)) return;

        var arrayAttr = GetAttribute(prop, Common.ArrayAttribute);
        if (arrayAttr != null)
        {
            GenerateArrayDeserialize(sb, prop, propAccess, arrayAttr);
            return;
        }

        if (GetAttribute(prop, "EdfCharArrayAttribute") != null && propType.SpecialType == SpecialType.System_String)
        {
            sb.AppendLine($"            reader.Read(out string? _{prop.Name});");
            sb.AppendLine($"            {propAccess} = _{prop.Name};");
            return;
        }

        if (propType.IsNullableValueType())
        {
            var underlying = propType.UnwrapNullable();
            sb.AppendLine($"            reader.Read(out bool _{prop.Name}_has);");
            sb.AppendLine($"            if (_{prop.Name}_has)");
            sb.AppendLine("            {");
            ReadPrimitiveOrComplex(sb, underlying, $"_{prop.Name}_val");
            sb.AppendLine($"                {propAccess} = _{prop.Name}_val;");
            sb.AppendLine("            }");
            sb.AppendLine("            else");
            sb.AppendLine("            {");
            sb.AppendLine($"                {propAccess} = null;");
            sb.AppendLine("            }");
            return;
        }

        ReadPrimitiveOrComplex(sb, propType, $"_{prop.Name}");
        sb.AppendLine($"            {propAccess} = _{prop.Name};");
    }

    private static void WritePrimitiveOrComplex(StringBuilder sb, ITypeSymbol type, string access)
    {
        if (type.SpecialType == SpecialType.System_String)
        {
            sb.AppendLine($"            writer.Write({access});");
        }
        else if (type.GetPrimitiveSize() > 0 || type.SpecialType == SpecialType.System_Boolean)
        {
            sb.AppendLine($"            writer.Write({access});");
        }
        else if (type.HasAttribute(Common.SerializeAttribute))
        {
            string typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            global::EdfNet.Interfaces.EdfProvider<{typeName}>.Formatter.Serialize(ref writer, {access}, options);");
        }
        else
        {
            sb.AppendLine($"            /* Unsupported serialize type: {type.ToDisplayString()} */");
        }
    }

    private static void ReadPrimitiveOrComplex(StringBuilder sb, ITypeSymbol type, string localVar)
    {
        if (type.SpecialType == SpecialType.System_String)
        {
            sb.AppendLine($"            reader.Read(out string? {localVar});");
        }
        else if (type.GetPrimitiveSize() > 0 || type.SpecialType == SpecialType.System_Boolean)
        {
            string typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            reader.Read(out {typeName} {localVar});");
        }
        else if (type.HasAttribute(Common.SerializeAttribute))
        {
            string typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            var {localVar} = global::EdfNet.Interfaces.EdfProvider<{typeName}>.Formatter.Deserialize(ref reader, options);");
        }
        else
        {
            sb.AppendLine($"            /* Unsupported deserialize type: {type.ToDisplayString()} */");
        }
    }

    private static void GenerateArraySerialize(StringBuilder sb, IPropertySymbol prop, string access, AttributeData arrayAttr)
    {
        var arrayType = prop.Type as IArrayTypeSymbol;
        var elementType = arrayType?.ElementType;

        if (elementType == null)
        {
            var named = prop.Type as INamedTypeSymbol;
            elementType = named?.TypeArguments.FirstOrDefault();
        }

        if (elementType == null)
        {
            sb.AppendLine($"            /* Cannot determine array element type for {prop.Name} */");
            return;
        }

        sb.AppendLine($"            writer.BeginArray();");
        sb.AppendLine($"            foreach (var _item in {access})");
        sb.AppendLine("            {");
        WritePrimitiveOrComplex(sb, elementType, "_item");
        sb.AppendLine("            }");
        sb.AppendLine($"            writer.EndArray();");
    }

    private static void GenerateArrayDeserialize(StringBuilder sb, IPropertySymbol prop, string access, AttributeData arrayAttr)
    {
        var arrayType = prop.Type as IArrayTypeSymbol;
        var elementType = arrayType?.ElementType;
        bool isArray = elementType != null;

        if (!isArray)
        {
            var named = prop.Type as INamedTypeSymbol;
            elementType = named?.TypeArguments.FirstOrDefault();
        }

        if (elementType == null)
        {
            sb.AppendLine($"            /* Cannot determine array element type for {prop.Name} */");
            return;
        }

        var dims = ExtractDimensions(arrayAttr);
        string propTypeName = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string elemTypeName = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string localVar = $"_{prop.Name}";

        if (isArray && dims.Count > 0)
        {
            sb.AppendLine($"            reader.ReadBeginArray();");

            if (arrayType!.Rank == 1)
            {
                sb.AppendLine($"            {propTypeName} {localVar} = new {elemTypeName}[{dims[0]}];");
                sb.AppendLine($"            for (int _i = 0; _i < {dims[0]}; _i++)");
                sb.AppendLine("            {");
                ReadPrimitiveOrComplex(sb, elementType, $"{localVar}[_i]");
                sb.AppendLine("            }");
            }
            else
            {
                sb.AppendLine($"            {propTypeName} {localVar} = new {elemTypeName}[{string.Join(", ", dims)}];");
                GenerateNestedLoops(sb, elementType, localVar, dims, 0, new List<string>());
            }

            sb.AppendLine($"            reader.ReadEndArray();");
            sb.AppendLine($"            {access} = {localVar};");
        }
        else
        {
            sb.AppendLine($"            /* Collection deserialization not fully implemented for {prop.Name} */");
        }
    }

    private static void GenerateNestedLoops(StringBuilder sb, ITypeSymbol elementType, string arrayVar, List<string> dims, int depth, List<string> indices)
    {
        if (depth >= dims.Count)
        {
            string indexAccess = string.Join(", ", indices);
            ReadPrimitiveOrComplex(sb, elementType, $"{arrayVar}[{indexAccess}]");
            return;
        }

        string idx = $"_i{depth}";
        sb.AppendLine($"            for (int {idx} = 0; {idx} < {dims[depth]}; {idx}++)");
        sb.AppendLine("            {");
        var newIndices = new List<string>(indices) { idx };
        GenerateNestedLoops(sb, elementType, arrayVar, dims, depth + 1, newIndices);
        sb.AppendLine("            }");
    }

    private static List<string> ExtractDimensions(AttributeData arrayAttr)
    {
        var result = new List<string>();
        if (arrayAttr.ConstructorArguments.Length > 0)
        {
            var arg = arrayAttr.ConstructorArguments[0];
            if (arg.Kind == TypedConstantKind.Array)
            {
                foreach (var v in arg.Values)
                {
                    result.Add(v.Value?.ToString() ?? "0");
                }
            }
        }
        return result;
    }

    private static bool IsIgnored(IPropertySymbol prop)
    {
        return prop.GetAttributes().Any(a =>
            a.AttributeClass?.ToDisplayString() == $"{Common.Namespace}.EdfIgnoreAttribute" ||
            a.AttributeClass?.Name == "EdfIgnoreAttribute");
    }

    private static AttributeData? GetAttribute(IPropertySymbol prop, string attributeName)
    {
        return prop.GetAttributes().FirstOrDefault(a =>
            a.AttributeClass?.ToDisplayString() == $"{Common.Namespace}.{attributeName}" ||
            a.AttributeClass?.Name == attributeName);
    }
}
