using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EdfGenerator;

[Generator]
public class EdfGenFormatter : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 2. Поиск классов с атрибутом [EdfSerializable]
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is TypeDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => Common.GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        // 3. Сборка данных для генерации (компиляция + список классов)
        IncrementalValuesProvider<INamedTypeSymbol> compilationAndClasses = classDeclarations.Select(static (s, _) => s!);

        // 4. Регистрация самого источника кода
        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) => Execute(spc, source));
    }

    private static void Execute(SourceProductionContext context, INamedTypeSymbol? structSymbol)
    {
        if (structSymbol is null) return;

        string namespaceName = structSymbol.ContainingNamespace.ToDisplayString();
        string structName = structSymbol.Name;
        string formatterName = $"{structName}Formatter";

        // Собираем свойства: базовые, вложенные сериализуемые и массивы
        var fields = structSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(f => !f.IsStatic
                        && (f.Type.IsCompatibleType() || f.Type is IArrayTypeSymbol)
                        && (f.DeclaredAccessibility == Accessibility.Public || f.DeclaredAccessibility == Accessibility.Internal))
            .ToList();

        if (fields.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using EdfNet.Interfaces;");
        sb.AppendLine("using EdfNet.Core;");
        sb.AppendLine("using EdfNet.Gen;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");

        sb.AppendLine($"public sealed class {formatterName} : IFormatter<{structName}>");
        sb.AppendLine("{");

        // Вызываем раздельные методы генерации
        GenerateInstance(sb, fields, structName, formatterName);
        GenerateSerialize(sb, fields, structName, formatterName);
        GenerateDeserialize(sb, fields, structName, formatterName);


        sb.AppendLine("}");
        

        context.AddSource($"{structName}Formatter.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));

    }

    private static void GenerateInstance(StringBuilder sb, List<IPropertySymbol> fields, string structName, string formatterName)
    {
        sb.AppendLine($"    public static {formatterName} Instance = new()");
        sb.AppendLine("");
    }
    private static void GenerateSerialize(StringBuilder sb, List<IPropertySymbol> fields, string structName, string enumeratorName)
    {
        sb.AppendLine($"    public void Serialize<TWriter>(ref TWriter writer,in {structName} val, EdfOptions options)");
        sb.AppendLine($"        where TWriter : struct, IBufWriter, allows ref struct");
        sb.AppendLine("    {");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
    private static void GenerateDeserialize(StringBuilder sb, List<IPropertySymbol> fields, string structName, string enumeratorName)
    {
        sb.AppendLine($"    public {structName} Deserialize<TReader>(ref TReader reader, EdfOptions options)");
        sb.AppendLine($"        where TReader : struct, IBufReader, allows ref struct");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {structName}();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }


    private static string GenerateResolver(string cases)
    {
        return @"// <auto-generated />
#nullable enable
using EdfNet.Interfaces;

namespace EdfNet.Generated
{
    public sealed class GeneratedEdfResolver : IFormatterResolver
    {
        public IFormatter<T>? GetFormatter<T>()
        {
" + cases + @"            return null;
        }
    }
}";
    }

}


