using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EdfGenerator;

[Generator]
public class EdfResolverGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var serializableTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is TypeDeclarationSyntax tds && tds.AttributeLists.Count > 0,
                transform: static (ctx, _) => Common.GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null)
            .Collect();

        context.RegisterSourceOutput(serializableTypes, static (spc, types) =>
        {
            if (types.IsDefaultOrEmpty) return;
            var distinctTypes = types.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>().ToList();
            if (distinctTypes.Count == 0) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("namespace EdfNet.Gen");
            sb.AppendLine("{");
            sb.AppendLine("    public sealed class GeneratedEdfResolver : global::EdfNet.Interfaces.IFormatterResolver");
            sb.AppendLine("    {");
            sb.AppendLine("        public global::EdfNet.Interfaces.IFormatter<T>? GetFormatter<T>()");
            sb.AppendLine("        {");

            foreach (var type in distinctTypes)
            {
                if (type is null) continue;
                string typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                string formatterName = type.ContainingNamespace.IsGlobalNamespace
                    ? $"{type.Name}Formatter"
                    : $"{type.ContainingNamespace.ToDisplayString()}.{type.Name}Formatter";

                sb.AppendLine($"            if (typeof(T) == typeof({typeName}))");
                sb.AppendLine($"                return (global::EdfNet.Interfaces.IFormatter<T>)(object)new {formatterName}();");
            }

            sb.AppendLine("            return null;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("GeneratedEdfResolver.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }
}
