using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace EdfGenerator;

[Generator]
public class EdfResolverGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var serializableTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is TypeDeclarationSyntax tds && tds.AttributeLists.Count > 0,
                transform: static (ctx, _) => Common.GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null)
            .Collect();

        context.RegisterSourceOutput(serializableTypes, static (spc, source) => Execute(spc, source));
    }
    private static void Execute(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> types)
    {
        if (types.IsDefaultOrEmpty) return;
        List<INamedTypeSymbol> distinctTypes = types.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>().ToList();
        if (distinctTypes.Count == 0) return;
        var sb = new StringBuilder();
        GeneratedEdfResolver(sb, distinctTypes);
        RegisterResolver(sb, distinctTypes);
        context.AddSource("GeneratedEdfResolver.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
    private static void GeneratedEdfResolver(StringBuilder sb, List<INamedTypeSymbol> distinctTypes)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using EdfNet.Interfaces;");
        sb.AppendLine();
        sb.AppendLine("namespace EdfNet.Gen;");
        sb.AppendLine("public class GeneratedEdfResolver : IFormatterResolver");
        sb.AppendLine("{");
        //sb.AppendLine("        public static GeneratedEdfResolver Instance { get; } = new GeneratedEdfResolver();");
        sb.AppendLine("    public IFormatter<T>? GetFormatter<T>()");
        sb.AppendLine("    {");

        foreach (var type in distinctTypes)
        {
            if (type is null) continue;
            string typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string formatterName = type.ContainingNamespace.IsGlobalNamespace
                ? $"{type.Name}Formatter"
                : $"{type.ContainingNamespace.ToDisplayString()}.{type.Name}Formatter";

            sb.AppendLine($"        if (typeof(T) == typeof({typeName}))");
            sb.AppendLine($"           return (IFormatter<T>)(object)new {formatterName}();");
        }

        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }
    private static void RegisterResolver(StringBuilder sb, List<INamedTypeSymbol> distinctTypes)
    {
        sb.AppendLine();
        sb.AppendLine("public static class GeneratedEdfResolverInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    public static void AutoRegister()");
        sb.AppendLine("    {");
        sb.AppendLine("        EdfNet.Interfaces.GlobalResolverRegistry.Register(new GeneratedEdfResolver());");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }
}
