using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EdfGenerator;

[Generator]
public class EdfSchemaGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Находим все типы с нужным атрибутом
        var typeDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is TypeDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => Common.GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);
        // 2. Собираем их в коллекцию (ImmutableArray), чтобы сгенерировать ОДИН файл для всего проекта
        // IncrementalValueProvider<ImmutableArray<INamedTypeSymbol>> compiledTypes = typeDeclarations.Collect()!;
        // 3. Сборка данных для генерации (компиляция + список классов)
        IncrementalValuesProvider<INamedTypeSymbol> compiledTypes = typeDeclarations.Select(static (s, _) => s!);
        // 3. Запускаем генерацию
        context.RegisterSourceOutput(compiledTypes, static (spc, source) => Execute(spc, source));
    }
    private static void Execute(SourceProductionContext context, INamedTypeSymbol? structSymbol)
    {
        if (structSymbol is null) return;

        string namespaceName = structSymbol.ContainingNamespace.ToDisplayString();
        string structName = structSymbol.Name;
        string enumeratorName = $"{structName}_EdfExtension";

        // Собираем свойства: базовые, вложенные сериализуемые и массивы
        var fields = structSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(f => !f.IsStatic
                        && (f.Type.IsCompatibleType() || f.Type is IArrayTypeSymbol)
                        && (f.DeclaredAccessibility == Accessibility.Public || f.DeclaredAccessibility == Accessibility.Internal))
            .ToList();

        if (fields.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using EdfNet.Interfaces;");
        sb.AppendLine("using EdfNet.Core;");
        sb.AppendLine("using EdfNet.Gen;");
        sb.AppendLine("using EdfSchema = EdfNet.Core.Schema;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine($"public static class {enumeratorName}");
        sb.AppendLine("{");
        // Вызываем раздельные методы генерации
        GenerateSchema(sb, fields, structName);
        sb.AppendLine("}");

        sb.AppendLine();
        //GeneratePartialEdfSerializable(sb, structName);

        context.AddSource($"{structName}_EdfExtension.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
    private static void GenerateSchema(StringBuilder sb, List<IPropertySymbol> fields, string structName)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Возвращает автоматически сгенерированный бинарный объект Schema для данного типа.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static EdfSchema GetEdfSchema{structName}()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new EdfSchema()");
        sb.AppendLine("        {");
        sb.AppendLine("            Id = 0,");
        sb.AppendLine($"            Name = \"{structName}Schema\",");
        sb.AppendLine($"            Desc = \"Schema for {structName} class\",");
        sb.AppendLine("             Type = new()");
        sb.AppendLine("            {");
        sb.AppendLine("                Type = PoType.Struct,");
        sb.AppendLine($"                Name = \"{structName}\",");
        sb.AppendLine("                Childs =");
        sb.AppendLine("                [");
        // Перебираем поля структуры/класса
        for (int i = 0; i < fields.Count; i++)
        {
            var f = fields[i];
            var fType = f.Type.UnwrapNullable();
            if (fType is IArrayTypeSymbol arraySymbol)
            {
                // Сценарий 1: Свойства-массивы (примитивы или вложенные объекты)
                string dimensionsStr = TypeSymbolUtils.ExtractArrayDimensions(f);
                string elemPoType = arraySymbol.ElementType.MapToPoType();

                if (!string.IsNullOrEmpty(elemPoType))
                {
                    // Массив примитивов, например: new (PoType.Int32, "Arr", [3, 2, 1])
                    sb.AppendLine($"                    new (PoType.{elemPoType}, \"{f.Name}\", [{dimensionsStr}]),");
                }
                else
                {
                    // Массив объектов: рекурсивно вытаскиваем Childs из энумератора вложенного типа
                    // Вид: new (PoType.Struct, "Sub", [2, 2]) { Childs = SubValByteEnumerator.GetEdfSchema().Type.Childs }
                    sb.AppendLine($"                    new (PoType.Struct, \"{f.Name}\", [{dimensionsStr}])");
                    sb.AppendLine("                    {");
                    sb.AppendLine($"                        Childs = {arraySymbol.ElementType.Name}.GetEdfSchema().Type.Childs");
                    sb.AppendLine("                    },");
                }
            }
            else if (fType.IsNestedSerializable())
            {
                // Сценарий 2: Одиночный вложенный сериализуемый объект (класс или структура)
                // Вид: new (PoType.Struct, "Sub0") { Childs = SubValByteEnumerator.GetEdfSchema().Type.Childs }
                sb.AppendLine($"                    new (PoType.Struct, \"{f.Name}\")");
                sb.AppendLine("                    {");
                sb.AppendLine($"                        Childs = {fType.Name}.GetEdfSchema().Type.Childs");
                sb.AppendLine("                    },");
            }
            else
            {
                // Сценарий 3: Обычный плоский базовый примитив
                // Вид: new (PoType.String, "Test1"),
                sb.AppendLine($"                    new (PoType.{fType.MapToPoType()}, \"{f.Name}\"),");
            }
        }
        sb.AppendLine("                ]");
        sb.AppendLine("            }");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    extension({structName})");
        sb.AppendLine("    {");
        sb.AppendLine($"        public static EdfSchema GetEdfSchema() => GetEdfSchema{structName}();");
        sb.AppendLine("    }");
        //sb.AppendLine();
        //sb.AppendLine($"        extension({structName} instance)");
        //sb.AppendLine("        {");
        //sb.AppendLine($"            public IEdfByteEnumerator<{structName}> GetByteEnumerator() => new {structName}ByteEnumerator(instance);");
        //sb.AppendLine("        }");

        sb.AppendLine();
        sb.AppendLine($"    public static {structName}ByteEnumerator GetByteEnumerator(this {structName} val)");
        sb.AppendLine($"        => new {structName}ByteEnumerator(val);");
        sb.AppendLine();
        sb.AppendLine($"    public static EdfErr WriteValue(this IWriter writer, {structName} val)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var enm = new {structName}ByteEnumerator(val);");
        sb.AppendLine($"        return writer.WriteEnumerator(ref enm);");
        sb.AppendLine("    }");
    }
    private static void GeneratePartialEdfSerializable(StringBuilder sb, string structName)
    {
        //sb.AppendLine($"public partial class {structName}: IEdfSerializable<{structName}ByteEnumerator>");
        sb.AppendLine($"public partial class {structName}: IEdfSerializable");
        sb.AppendLine("{");
        //sb.AppendLine($"    public {structName}ByteEnumerator GetByteEnumerator() " +
        //sb.AppendLine($"    public {structName}ByteEnumerator GetByteEnumerator() " +
        sb.AppendLine($"    public IEdfByteEnumerator GetByteEnumerator() " +
                      $"=> new {structName}ByteEnumerator(this);");

        sb.AppendLine($"    public static IEdfByteEnumerator GetByteEnumerator({structName} val) " +
                      $"=> new {structName}ByteEnumerator(val);");

        sb.AppendLine("    public EdfErr WriteTo<TWriter>(TWriter writer) where TWriter : IWriter");
        sb.AppendLine("    {");
        sb.AppendLine($"        var enm = new {structName}ByteEnumerator(this);");
        sb.AppendLine($"        return writer.WriteEnumerator(ref enm);");
        sb.AppendLine("    }");

        sb.AppendLine("}");
    }
}
