using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EdfGenerator;

[Generator]
public class EdfSchemaGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Находим все типы с нужным атрибутом
        var typeDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is TypeDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => Common.GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);
        // 2. Собираем их в коллекцию (ImmutableArray), чтобы сгенерировать ОДИН файл для всего проекта
        // IncrementalValueProvider<ImmutableArray<INamedTypeSymbol>> compiledTypes = typeDeclarations.Collect()!;
        // 3. Сборка данных для генерации (компиляция + список классов)
        IncrementalValuesProvider<INamedTypeSymbol> compiledTypes = typeDeclarations.Select(static (s, _) => s!);
        // 3. Запускаем генерацию
        context.RegisterSourceOutput(compiledTypes, static (spc, source) => Execute(spc, source));
    }
    private static IEnumerable<ISymbol> GetSerializableMembers(INamedTypeSymbol type)
    {
        return type.GetMembers()
            .Where(m => m is IPropertySymbol || m is IFieldSymbol)
            .Where(m => m.DeclaredAccessibility == Accessibility.Public)
            .Where(m => m.IsSupportedMemberType());
    }
    private static void Execute(SourceProductionContext context, INamedTypeSymbol? structSymbol)
    {
        if (structSymbol is null) return;

        string namespaceName = structSymbol.ContainingNamespace.ToDisplayString();
        string typeName = TypeSymbolUtils.GetShortTypeName(structSymbol, namespaceName);
        string typeLabel = typeName.Replace(".", "_");

        // Собираем свойства: базовые, вложенные сериализуемые и массивы
        var fields = GetSerializableMembers(structSymbol).ToList();

        if (fields.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using EdfNet.Interfaces;");
        sb.AppendLine("using EdfNet.Core;");
        sb.AppendLine("using EdfNet.Extensions;");
        sb.AppendLine("using EdfNet.Gen;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine($"public static class {typeLabel}_EdfExtension");
        sb.AppendLine("{");
        // Вызываем раздельные методы генерации
        GenerateSchema(sb, fields, structSymbol, namespaceName);
        sb.AppendLine("}");

        sb.AppendLine();
        //GeneratePartialEdfSerializable(sb, structName);

        context.AddSource($"{typeLabel}_EdfExtension.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
    private static void GenerateSchema(StringBuilder sb, List<ISymbol> fields, INamedTypeSymbol structSymbol, string ns)
    {
        string typeName = TypeSymbolUtils.GetShortTypeName(structSymbol, ns);
        structSymbol.ExtractSerialize(out var id, out var name, out var desc);
        string typeLabel = typeName.Replace(".", "_");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Возвращает автоматически сгенерированный бинарный объект Schema для данного типа.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static EdfSchema GetEdfSchema_{typeLabel}()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new EdfSchema()");
        sb.AppendLine("        {");
        sb.AppendLine($"            Id = {id},");
        sb.AppendLine($"            Name = \"{name}\",");
        sb.AppendLine($"            Desc = \"{desc}\",");
        sb.AppendLine("             Type = new()");
        sb.AppendLine("            {");
        sb.AppendLine("                Type = EdfPrimitiveType.Struct,");
        sb.AppendLine($"                Name = \"{typeName}\",");
        sb.AppendLine("                Childs =");
        sb.AppendLine("                [");
        // Перебираем поля структуры/класса
        for (int i = 0; i < fields.Count; i++)
        {
            var f = fields[i];
            var fType = f.GetMemberType()?.UnwrapNullable();
            if (fType is IArrayTypeSymbol arraySymbol)
            {
                // Сценарий 1: Свойства-массивы (примитивы или вложенные объекты)
                string dimensionsStr = TypeSymbolUtils.ExtractArrayDimensions(f);
                string elemEdfPrimitiveType = arraySymbol.ElementType.MapToEdfPrimitiveType();

                if (!string.IsNullOrEmpty(elemEdfPrimitiveType))
                {
                    // Массив примитивов, например: new (EdfPrimitiveType.Int32, "Arr", [3, 2, 1])
                    sb.AppendLine($"                    new (EdfPrimitiveType.{elemEdfPrimitiveType}, \"{f.Name}\", [{dimensionsStr}]),");
                }
                else
                {
                    // Массив объектов: рекурсивно вытаскиваем Childs из энумератора вложенного типа
                    // Вид: new (EdfPrimitiveType.Struct, "Sub", [2, 2]) { Childs = SubValByteEnumerator.GetEdfSchema().Type.Childs }
                    sb.AppendLine($"                    new (EdfPrimitiveType.Struct, \"{f.Name}\", [{dimensionsStr}])");
                    sb.AppendLine("                    {");
                    sb.AppendLine($"                        Childs = {TypeSymbolUtils.GetShortTypeName(arraySymbol.ElementType, ns)}.GetEdfSchema().Type.Childs");
                    sb.AppendLine("                    },");
                }
            }
            else if (true == fType?.IsNestedSerializable())
            {
                // Сценарий 2: Одиночный вложенный сериализуемый объект (класс или структура)
                // Вид: new (EdfPrimitiveType.Struct, "Sub0") { Childs = SubValByteEnumerator.GetEdfSchema().Type.Childs }
                sb.AppendLine($"                    new (EdfPrimitiveType.Struct, \"{f.Name}\")");
                sb.AppendLine("                    {");
                sb.AppendLine($"                        Childs = {TypeSymbolUtils.GetShortTypeName(fType, ns)}.GetEdfSchema().Type.Childs");
                sb.AppendLine("                    },");
            }
            else
            {
                // Сценарий 3: Обычный плоский базовый примитив
                // Вид: new (EdfPrimitiveType.String, "Test1"),
                sb.AppendLine($"                    new (EdfPrimitiveType.{fType!.MapToEdfPrimitiveType()}, \"{f.Name}\"),");
            }
        }
        sb.AppendLine("                ]");
        sb.AppendLine("            }");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    extension({typeName})");
        sb.AppendLine("    {");
        sb.AppendLine($"        public static EdfSchema GetEdfSchema() => GetEdfSchema_{typeLabel}();");
        sb.AppendLine("    }");
    }
}
